@startuml
hide empty description

skinparam Arrow {
  FontSize 9
}

state comp as "Node" {


state Advertising
state Connecting
state Connected

state CP_whitelisted as "Whitelisted?"

[*] --> Advertising

Advertising --> Advertising : Timeout

Advertising --> CP_whitelisted : RTx:ConnectReq


CP_whitelisted -> Connecting : Yes
CP_whitelisted -up-> Advertising : No

Connecting --> Advertising : Timeout

Connecting -> Connected : RTX:ConnectedInd
Connected --> Advertising : RTx:DisconnectInd
Connected --> Advertising : Timeout

Connected --> Connected : RTx:ConectedInd
}
@enduml