@startuml
:Actor A: --> (Use case A)
:Actor A: --> (Use case C)
:Actor B: --> (Use case A)
:Actor B: --> (Use case B)
:Actor B: --> (Use case C)
:Actor B: --> (Use case D)
:Actor C: --> (Use case B)
:Actor C: --> (Use case D)
:Actor C: --> (Use case C)
(Use case A) --> (Use case B)
@enduml